reorder_python_imports/main.py, tests/main_test.py
=> Add a --print-only output format

reorder_python_imports/main.py, tests/main_test.py
To support separate `from xx import xx` imports from `import xx` imports
with an new line.
Closes #19.
=> Add an option `--separate-from-import`

reorder_python_imports/main.py, tests/main_test.py
=> Fix when both --separate-from and --separate-relative are passed.

reorder_python_imports/main.py, tests/main_test.py
=> Add --py_-plus options to remove old future imports

tests/conftest.py, tests/reorder_python_imports_test.py
Committed via https://github.com/asottile/all-repos
=> Replace deprecated yield_fixture with fixture

reorder_python_imports.py, tests/reorder_python_imports_test.py
- validate that the arguments are import statements
- allow adding / removing multiple imports at once
=> Improve --add-import / --remove-import

reorder_python_imports.py, tests/reorder_python_imports_test.py
=> Handle non-unix line endings properly

.pre-commit-config.yaml, reorder_python_imports.py
Committed via https://github.com/asottile/all-repos
=> Run pre-commit autoupdate

reorder_python_imports.py, requirements-dev.txt, tests/reorder_python_imports_test.py, tox.ini
Similar to https://github.com/asottile/add-trailing-comma/pull/75, I'm adding '-' as an option for editor tooling.
=> Add '-', Deprecate '--print-only'

.gitignore, .pre-commit-config.yaml, reorder_python_imports.py, testing/generate-six-info, tests/reorder_python_imports_test.py
=> Also remove imports from `builtins` due to python-future

.pre-commit-config.yaml, azure-pipelines.yml, reorder_python_imports.py, requirements-dev.txt, setup.cfg, testing/generate-six-info, tests/reorder_python_imports_test.py, tox.ini
[python 3 statement](https://github.com/asottile/scratch/wiki/python-3-statement)
=> reorder-python-imports: python3.6+

reorder_python_imports.py
=> Added help str for filenames and reference to `-` in `--print-only`

tests/reorder_python_imports_test.py
=> Add a regression test

reorder_python_imports.py, tests/reorder_python_imports_test.py
=> Fix option --diff-only not working with stdin input

setup.cfg, testing/generate-mock-info, testing/generate-six-info
Committed via https://github.com/asottile/all-repos
=> stricter mypy settings

.pre-commit-config.yaml, reorder_python_imports.py
Committed via https://github.com/asottile/all-repos
=> upgrade flake8-typing-imports

setup.cfg, tests/reorder_python_imports_test.py
=> ensure `import __future__` sorts as standard library

reorder_python_imports.py, tests/reorder_python_imports_test.py
from some quick measurements this improves perf by about 30% -- and is significantly simpler!
=> improve performance by avoiding NodeVisitor

reorder_python_imports.py, tests/reorder_python_imports_test.py
oops, I accidentally broke these in #268
=> fix multiline imports

README.md
Adding a documented example for this case since it confused me until I read the docs more closely
=> Add another README example for "non-whitespace non-comment lines will be ignored"
